# Kafka cluster replication configuration
x-common-variables: &kafka-common-variables
  KAFKA_MIN_INSYNC_REPLICAS: 2
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_NUM_PARTITIONS: 2

services:
# Kafka cluster with 3 brokers and Zookeeper
  zookeeper:
    image: zookeeper:3.9.3
    restart: unless-stopped
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - local-kafka
    ports:
      - 2181:2181
    volumes:
      - ./data/zookeeper1/data:/data
      - ./data/zookeeper1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka_broker_1:
    image: confluentinc/cp-kafka:7.8.0
    restart: unless-stopped
    hostname: kafka_broker_1
    container_name: kafka_broker_1
    networks:
      - local-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    environment:
      <<: *kafka-common-variables
      KAFKA_CLUSTER_ID: kafka-cluster
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:9092,PLAINTEXT://kafka_broker_1:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka_broker_2:
    image: confluentinc/cp-kafka:7.8.0
    restart: unless-stopped
    hostname: kafka_broker_2
    container_name: kafka_broker_2
    networks:
      - local-kafka
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
    volumes:
      - ./data/kafka2/data:/var/lib/kafka/data
    environment:
      <<: *kafka-common-variables
      KAFKA_CLUSTER_ID: kafka-cluster
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:9094,PLAINTEXT://kafka_broker_2:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka_broker_3:
    image: confluentinc/cp-kafka:7.8.0
    restart: unless-stopped
    hostname: kafka_broker_3
    container_name: kafka_broker_3
    networks:
      - local-kafka
    depends_on:
      - zookeeper
    ports:
      - 9096:9096
    volumes:
      - ./data/kafka3/data:/var/lib/kafka/data
    environment:
      <<: *kafka-common-variables
      KAFKA_CLUSTER_ID: kafka-cluster
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:9096,PLAINTEXT://kafka_broker_3:9097
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

# Schema Registry
  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0
    hostname: schema-registry
    container_name: schema-registry
    networks:
      - local-kafka
    depends_on:
      - kafka_broker_1
      - kafka_broker_2
      - kafka_broker_3
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka_broker_1:9093,kafka_broker_2:9095,kafka_broker_3:9097
      SCHEMA_REGISTRY_DEBUG: true

# Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    networks:
      - local-kafka
    depends_on:
      - kafka_broker_1
      - kafka_broker_2
      - kafka_broker_3
    ports:
      - 28080:8080
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka_broker_1:9093,kafka_broker_2:9095,kafka_broker_3:9097
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

# Automatically create a topic when the container starts
  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka_broker_1
      - kafka_broker_2
      - kafka_broker_3
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=spcd-main-topic --if-not-exists --bootstrap-server=kafka_broker_1:9093"

# Network configuration
networks:
  local-kafka:
    driver: bridge